#!/bin/bash
# Dump the Requestick database to ./backups/mesh-YYYY-MM-DD.sql.gz
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/mesh.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "mesh.env not found. Run install.sh first."
  exit 1
fi
# shellcheck disable=SC1090
set -a
# mesh.env is KEY=value with no export; source it.
# The file is generated by install.sh and is not committed.
source "$ENV_FILE"
set +a
mkdir -p "$ROOT/backups"
STAMP="$(date -u +%Y-%m-%dT%H%M%SZ)"
OUT="$ROOT/backups/mesh-${STAMP}.sql.gz"
docker compose --env-file "$ENV_FILE" exec -T db \
  pg_dump -U mesh -d mesh --no-owner --clean --if-exists \
  | gzip > "$OUT"
echo "Wrote $OUT"
# Keep the last 30 dumps
ls -1t "$ROOT/backups"/mesh-*.sql.gz 2>/dev/null | tail -n +31 | xargs -r rm --
